site_name: Haiway Documentation
site_description: Framework for dependency injection and state management within structured concurrency model
site_url: https://miquido.github.io/haiway/
repo_url: https://github.com/miquido/haiway
repo_name: miquido/haiway
edit_uri: edit/main/docs/

theme:
  name: material
  custom_dir: docs/overrides
  palette:
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.indexes
    - toc.follow
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
    - content.code.copy
    - content.code.select
    - content.code.annotate
    
  icon:
    repo: fontawesome/brands/github
    
  font:
    text: Inter
    code: JetBrains Mono

extra_css:
  - stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/miquido/haiway
    - icon: fontawesome/solid/globe
      link: https://miquido.com
      
copyright: Copyright &copy; 2024 Miquido

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - tables
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: miquido
      repo: haiway
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
  - search:
      lang: en
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_source: true
            show_root_heading: true
            show_root_full_path: false
            merge_init_into_class: true
            show_signature_annotations: true
            separate_signature: true

nav:
  - Home: index.md
  - Getting Started:
    - getting-started/index.md
    - Installation: getting-started/installation.md
    - Quick Start: getting-started/quickstart.md
    - First Steps: getting-started/first-steps.md
  - Guides:
    - guides/index.md
    - Architecture: guides/architecture.md
    - State Management: guides/state-management.md
    - Context System: guides/context-system.md
    - Async Patterns: guides/async-patterns.md
    - Testing: guides/testing.md
  - API Reference:
    - api/index.md
    - Core: api/core.md
    - Context: api/context.md
    - State: api/state.md
    - Helpers: api/helpers.md
    - Types: api/types.md
  - Examples:
    - examples/index.md
    - FastAPI Integration: examples/fastapi-integration.md
  - Advanced:
    - advanced/index.md
    - Performance: advanced/performance.md
    - Troubleshooting: advanced/troubleshooting.md