name: Docs

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1 – Checkout code
      - uses: actions/checkout@v4

      # 2 – Install Python 3.12 (matches your project)
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      # 3 – Install doc toolchain
      - name: Install docs dependencies
        run: |
          python -m pip install --upgrade pip
          pip install \
            mkdocs~=1.6 \
            mkdocs-material~=9.5 \
            mkdocstrings[python]~=0.27 \
            pymdown-extensions~=10.12 \
            pydoc-markdown~=4.8

      # 4 – Generate API reference (optional but harmless)
      - name: Build API reference
        run: make api-reference-docs-build

      # 5 – Build the static site
      - name: Build MkDocs site
        run: mkdocs build --strict          # output goes into ./site

      # 6 – Upload site as Pages artifact
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site                        # <-- MkDocs output dir

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: github-pages
    steps:
      # 7 – Deploy to gh-pages
      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4
